import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import React from "react";
import Link from "next/link";
import ThemeToggle from "../components/ThemeToggle";
import Script from 'next/script';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Navbar() {
  return (
      <nav className="bg-primary-strong text-on-primary p-4 flex justify-between items-center">
      <div className="font-bold text-lg">
          <Link href="/" className="hover:text-primary">CLP Flow</Link>
      </div>
          <div className="flex items-center space-x-4">
              <div className="space-x-4 hidden sm:inline">
                  <Link href="/" className="hover:text-primary">Home</Link>
                  <Link href="/results" className="hover:text-primary">Data</Link>
                  <Link href="/chatbot" className="hover:text-primary">Chatbot</Link>
              </div>
              <div className="flex items-center space-x-4">
                  <ThemeToggle/>
              </div>
      </div>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      {/* Inline script to apply saved theme before React hydrates (prevents FOUC and ensures Tailwind 'dark' class is present) */}
      <Script id="theme-init" strategy="beforeInteractive">
          {`(function(){try{var t=localStorage.getItem('theme');var el=document.body; if(t==='dark'){el.classList.add('dark'); el.classList.remove('light');} else {el.classList.add('light'); el.classList.remove('dark');}}catch(e){} })();`}
      </Script>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
